name: TeleportBow
main: dev.finny.teleportbow.TeleportBow
version: ${project.version}
api-version: "1.20"
author: "Finny"

commands:
  givebow:
    usage: /givebow
    description: "Give a bow"
    # permission: "tpbow.give"
# permissions:
#   tpbow.give:
#     default: false
#     description: Allows the use of /givebow
