name: TeleportBow
main: dev.finny.teleportbow.TeleportBow
version: ${project.version}
api-version: "1.20"
author: "Finny"

commands:
  givebow:
    usage: /givebow
    description: "Give a bow"
    permission: "tpbow.give"
    permission-message: You do not have access to this command.

permissions:
  tpbow.give:
    default: op
    description: Allows the use of /givebow
